# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/sunxinyu/Workspace/face/ui/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1230, 763)
        MainWindow.setMinimumSize(QtCore.QSize(1230, 763))
        MainWindow.setMaximumSize(QtCore.QSize(1230, 763))
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/sunxinyu/Workspace/face/ui/resources/icon1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imgLabel = QtWidgets.QLabel(self.centralwidget)
        self.imgLabel.setGeometry(QtCore.QRect(10, 10, 1080, 720))
        self.imgLabel.setStyleSheet("background-color: rgb(199, 199, 199);\n"
"border:1px solid rgb(144, 144, 144);")
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.roiLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.roiLabel1.setGeometry(QtCore.QRect(1110, 10, 100, 100))
        self.roiLabel1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.roiLabel1.setStyleSheet("QLabel{\n"
"    background-color: rgb(199, 199, 199);\n"
"    border:1px solid rgb(144, 144, 144);\n"
"}\n"
"QLabel:hover{\n"
"    background-color: rgb(229, 241, 251);\n"
"    border:1px solid rgb(0, 120, 215);\n"
"}\n"
"QLabel:pressed{\n"
"    background-color: rgb(229, 241, 251);\n"
"    border:1px solid rgb(100, 120, 215);\n"
"}\n"
"")
        self.roiLabel1.setText("")
        self.roiLabel1.setPixmap(QtGui.QPixmap("/Users/sunxinyu/Workspace/face/ui/resources/icon1.ico"))
        self.roiLabel1.setObjectName("roiLabel1")
        self.roiLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.roiLabel2.setGeometry(QtCore.QRect(1110, 140, 100, 100))
        self.roiLabel2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.roiLabel2.setStyleSheet("QLabel{\n"
"    background-color: rgb(199, 199, 199);\n"
"    border:1px solid rgb(144, 144, 144);\n"
"}\n"
"QLabel:hover{\n"
"    background-color: rgb(229, 241, 251);\n"
"    border:1px solid rgb(0, 120, 215);\n"
"}\n"
"")
        self.roiLabel2.setText("")
        self.roiLabel2.setObjectName("roiLabel2")
        self.roiLabel3 = QtWidgets.QLabel(self.centralwidget)
        self.roiLabel3.setGeometry(QtCore.QRect(1110, 270, 100, 100))
        self.roiLabel3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.roiLabel3.setStyleSheet("QLabel{\n"
"    background-color: rgb(199, 199, 199);\n"
"    border:1px solid rgb(144, 144, 144);\n"
"}\n"
"QLabel:hover{\n"
"    background-color: rgb(229, 241, 251);\n"
"    border:1px solid rgb(0, 120, 215);\n"
"}\n"
"")
        self.roiLabel3.setText("")
        self.roiLabel3.setObjectName("roiLabel3")
        self.roiLabel4 = QtWidgets.QLabel(self.centralwidget)
        self.roiLabel4.setGeometry(QtCore.QRect(1110, 400, 100, 100))
        self.roiLabel4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.roiLabel4.setStyleSheet("QLabel{\n"
"    background-color: rgb(199, 199, 199);\n"
"    border:1px solid rgb(144, 144, 144);\n"
"}\n"
"QLabel:hover{\n"
"    background-color: rgb(229, 241, 251);\n"
"    border:1px solid rgb(0, 120, 215);\n"
"}\n"
"")
        self.roiLabel4.setText("")
        self.roiLabel4.setObjectName("roiLabel4")
        self.name1 = QtWidgets.QLabel(self.centralwidget)
        self.name1.setGeometry(QtCore.QRect(1110, 110, 100, 30))
        self.name1.setAlignment(QtCore.Qt.AlignCenter)
        self.name1.setObjectName("name1")
        self.name2 = QtWidgets.QLabel(self.centralwidget)
        self.name2.setGeometry(QtCore.QRect(1110, 240, 100, 30))
        self.name2.setAlignment(QtCore.Qt.AlignCenter)
        self.name2.setObjectName("name2")
        self.name3 = QtWidgets.QLabel(self.centralwidget)
        self.name3.setGeometry(QtCore.QRect(1110, 370, 100, 30))
        self.name3.setAlignment(QtCore.Qt.AlignCenter)
        self.name3.setObjectName("name3")
        self.name4 = QtWidgets.QLabel(self.centralwidget)
        self.name4.setGeometry(QtCore.QRect(1110, 500, 100, 30))
        self.name4.setAlignment(QtCore.Qt.AlignCenter)
        self.name4.setObjectName("name4")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(1120, 680, 80, 30))
        self.button2.setStyleSheet("")
        self.button2.setObjectName("button2")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(1120, 640, 80, 30))
        self.button1.setStyleSheet("")
        self.button1.setObjectName("button1")
        self.line1 = QtWidgets.QLineEdit(self.centralwidget)
        self.line1.setGeometry(QtCore.QRect(1110, 530, 101, 21))
        self.line1.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.line1.setObjectName("line1")
        self.line2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line2.setGeometry(QtCore.QRect(1110, 560, 101, 21))
        self.line2.setObjectName("line2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setEnabled(True)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1230, 24))
        self.menuBar.setObjectName("menuBar")
        self.menu1 = QtWidgets.QMenu(self.menuBar)
        self.menu1.setObjectName("menu1")
        self.menu2 = QtWidgets.QMenu(self.menuBar)
        self.menu2.setObjectName("menu2")
        MainWindow.setMenuBar(self.menuBar)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.menu1.addAction(self.action1)
        self.menu2.addAction(self.action2)
        self.menuBar.addAction(self.menu1.menuAction())
        self.menuBar.addAction(self.menu2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name1.setText(_translate("MainWindow", "用户0"))
        self.name2.setText(_translate("MainWindow", "用户1"))
        self.name3.setText(_translate("MainWindow", "用户2"))
        self.name4.setText(_translate("MainWindow", "用户3"))
        self.button2.setText(_translate("MainWindow", "退出"))
        self.button1.setText(_translate("MainWindow", "保存人脸"))
        self.menu1.setTitle(_translate("MainWindow", "文件"))
        self.menu2.setTitle(_translate("MainWindow", "编辑"))
        self.action1.setText(_translate("MainWindow", "所有用户"))
        self.action2.setText(_translate("MainWindow", "退出"))
